### ISSUE TITLE
还想起一个：地址，address

### ISSUE THREAD

**Issue by CallMeZhou** [shimohq/chinese-programmer-wrong-pronunciation#33]
不同重音，完全是两个词。至少我自己以前一直读成“解决”那个词了。
------------------
还是补充一下：在美语里，动词的address念/əˈdres/，当deal with或者speak to讲；而名词的则念/ˈæd.res/，当地址讲。所以当说美国英语的人跟你讲内存地址时，他会说/ˈmeməri ˈæd.res/。但是貌似英国人总是念/əˈdres/的。

来源：http://dictionary.cambridge.org/dictionary/english/address

**Comment by wanming** [comment]
"解决" 哪个词?

**Comment by brunobell** [comment]
this is really a good issue. for the word address, pronunciation really varies depending on whether it's a noun or verb and the situation as well, view [here ](https://www.merriam-webster.com/dictionary/address)for details on merriam-webster

**Comment by lilydjwg** [comment]
我好像没听到过读成 [ædˌres] 的。这是个很奇怪的发音啊。我从来没见过词内 d 和 r 音分开读的情况。

**Comment by yougg** [comment]
@lilydjwg 你去看看日本那边的读音, 他们全部都拆开读, 我也是醉了.
tr拆开读t,r
dr拆开读d,r

**Comment by brunobell** [comment]
@yougg it's not just about Japanese people, people in India, the Middle East and Korea seems to say it in the way your just mentioned, that is, separating /t/ and /d/ with /r/ sound. I guess that's because in their own languages the tinest bits of phonetic alphabets are not as complicated as the English /tr/ or /dr/. Anyway, language is just a tool to get you understood. If he has no problem communicating with others, why would you bother?

**Comment by lilydjwg** [comment]
@brunobell I won't bother if
* they don't communicate with me
* they don't speak in front of me, making me familiar with the wrong pronunciations, confusing me, and finally making me failed to be understood when communicating with natives.

**Comment by brunobell** [comment]
@lilydjwg I agree with you on that:
long period of communication with people speaking with non-standard pronunciations DO confuse the the other party and MIGHT even to some degree assimilate the listener.
yet basically I doubt it that you'd fail to get understood by natives since:
as Chinese you'll have no problem understanding all flavors of accents and distortions and exaggerations when a foreigner tries to speak elementary level Chinese
anyway, individual opinions won't bite :)

**Comment by CallMeZhou** [comment]
@wanming 在美语发音里，Address若重音在后，念成“呃拽丝”，就当“解决”讲。若重音在前，念成“挨拽丝”，就是“地址”。但据说，英国发音则全部念成重音在后。我没有做深入的考证，只是根据dictionary.cambridge.org。

**Comment by CallMeZhou** [comment]
@lilydjwg @yougg /ˈæd.res/中间那个小“.”不是表示分开读，而是“次重音”，我记得中学学音标时老师讲过的啊？

**Comment by CallMeZhou** [comment]
@yougg 日本……不是有个活生生的例子吗？比如“哆啦A梦” :D

**Comment by lilydjwg** [comment]
@CallMeZhou 我看过那个网站的标音了。那个小东西似乎是某个连字符，表示它俩是一个音。次重音我认识，是这个 `ˌ`。它出现在一个音节的前边，不会出现在一个音的中间。

@brunobell yes natives always are super-great with distorted pronunciations, but it still take time to figure out some pronunciations, and, there may be non-natives from other countries, or even Chinese with other pronunciations (e.g. a Chinese I encountered pronounced "older" for "order"....).

**Comment by wanming** [comment]
interesting
